### ISSUE TITLE
Add new light switches

### ISSUE THREAD

**Issue by RavidCo** [nitaybz/homebridge-switcher-platform#45] opened 2023-05-22 08:54 UTC
Hi, recently Switcher added new light switches, I would appreciate it if you could add them that will also support homekit

**Comment by gavrie** [comment] 2023-05-28 09:03
I think this is a duplicate of #42

**Comment by RavidCo** [comment] 2023-05-28 10:07
You're right, now I notice. 

Can you guess when the plugin will be supported?

**Comment by gavrie** [comment] 2023-05-28 10:16
I don't know how much this project is being maintained, so no idea... I may give it a try myself, but the problem is finding the time 😄

**Comment by RavidCo** [comment] 2023-05-28 10:36
Oh sorry, I thought you were Nitay 
I assume he will find the time to sit on it, 

regarding taking on the project, I understand less about it and therefore cannot express an opinion on the matter

**Comment by nitaybz** [comment] 2023-06-04 05:59
working on it... closing as this is duplicate of #42

**Closed by nitaybz** 2023-06-04 05:59 UTC
