### ISSUE TITLE
Switcher v3 (touch) turning itself off - not working

### ISSUE THREAD

**Issue by avielc** [nitaybz/homebridge-switcher-platform#46] opened 2023-06-18 07:45 UTC
Hi Nitay
Thanks for the great module for homebridge, a real life changer
I think a week ago or so it stopped working. 
I can turn it on through the switcher app, but the Homebridge doesn't work - turning it will will make it turn off on its own after a few seconds. and if I turn it from the switcher app it displays the on status correctly - (e.g. view only) 
(sounds like #13  issue) 
However I don't see an option to update the firmware there
at the moment it's on firmware 5.15
Using an iphone 
Need any other info?

**Comment by sobelman** [comment] 2023-11-28 18:32
Hi, 
Adding my case as well, 

I have 3 units (switcher touch) 

2 units running version 5.15
1 unit running version 3.22 

both units running 5.15 have the same symptoms e.g. “view only”  via homebridge / HomeKit but works normally via native switcher app. 

The unit running with version 3.22 working as expected. 

HB server running with latest versions, 
Everything is auto configured and no unique configs were set. 

Plugin was removed and reinstalled with the same behavior. 

‘Local’ on/off was tested as well with no changes as well. 

Setup is: 
- OS Ubuntu Jammy Jellyfish 22.04.3 LTS
- Homebridge v1.7.0
- UI v4.53.0
- Node.js Version: v20.10.0
- homebridge-switcher-platform v4.4.4


Any support will be appreciated 🙏🇮🇱⚔️⛈️

**Comment by nitaybz** [comment] 2023-12-12 16:02
Please update to the latest version and let me know if the issue is fixed

**Comment by avielc** [comment] 2023-12-12 16:08
5.15 is the latest firmware version

**Comment by nitaybz** [comment] 2023-12-12 16:11
I mean the plugin version, install 4.4.5

**Comment by nitaybz** [comment] 2023-12-12 16:34
Closing cause it's the same as #52

**Closed by nitaybz** 2023-12-12 16:34 UTC
