### ISSUE TITLE
Power plug control not working, status does get updated

### ISSUE THREAD

**Issue by Three141** [nitaybz/homebridge-switcher-platform#50] opened 2023-08-21 19:59 UTC
I have [Switcher Smart Plug](https://switcher.co.il/%D7%9E%D7%95%D7%A6%D7%A8/%D7%A1%D7%95%D7%95%D7%99%D7%A6%D7%A8-smart-plug/) and I can't bring it to work with Homebridge.
The outlet status gets updated in Homebridge UI and HomeKit, but whenever I try to change the state (turn on or turn off), it just doesn't work.
The token has been set and Switcher Mini works flawlessly

logs:
```
[21/08/2023, 22:56:12] [Switcher Platform] Turning ON Power_plug_6422 
[21/08/2023, 22:56:12] [Switcher Platform] login...
[21/08/2023, 22:56:12] [Switcher Platform] successful connection, socket was created
[21/08/2023, 22:56:12] [Switcher Platform] sending data
[21/08/2023, 22:56:12] [Switcher Platform] fef052000232a100000000003400010000000000000000005cc1e36400000000000000000000f0fe1c00000000000000000000000000000000000000000000000000000000000000000000000000428f9a17
[21/08/2023, 22:56:12] [Switcher Platform] received login data:
[21/08/2023, 22:56:12] [Switcher Platform] fef02c00023ca100000000003400020e0000f932220000005bc1e36400000000000000000000f0fe43b9ddd2
[21/08/2023, 22:56:12] [Switcher Platform] received session id: 00000000
[21/08/2023, 22:56:12] [Switcher Platform] sending ON command
[21/08/2023, 22:56:12] [Switcher Platform] sending data:
[21/08/2023, 22:56:12] [Switcher Platform] fef05d0002320102000000003400010000000000000000005cc1e36400000000000000000000f0fef9322200000000000000000000000000000000000000000000000000000000000000000000000000010600010000000000eb0594d4
[21/08/2023, 22:56:12] [Switcher Platform] connection closed, had error: false
[21/08/2023, 22:56:12] [Switcher Platform] global close event: false
```

Power plug firmware version: 5.09

**Comment by andybenichou** [comment] 2023-08-31 09:48
I got the same error from a Switcher Touch for turning on/off hot water:

My logs:
`[31/08/2023, 12:44:33] [Switcher Platform] Turning ON SwitcherTouch 
[31/08/2023, 12:44:33] [Switcher Platform] login...
[31/08/2023, 12:44:33] [Switcher Platform] successful connection, socket was created
[31/08/2023, 12:44:33] [Switcher Platform] sending data
[31/08/2023, 12:44:33] [Switcher Platform] fef052000232a100000000003400010000000000000000000161f06400000000000000000000f0fe1c00000000000000000000000000000000000000000000000000000000000000000000000000cf89e4dd
[31/08/2023, 12:44:33] [Switcher Platform] Switcher SwitcherTouch is INACTIVE
[31/08/2023, 12:44:33] [Switcher Platform] received login data:
[31/08/2023, 12:44:33] [Switcher Platform] fef02c00023ca100000000003400020e00006530650000000161f06400000000000000000000f0fe57b524e8
[31/08/2023, 12:44:33] [Switcher Platform] received session id: 00000000
[31/08/2023, 12:44:33] [Switcher Platform] sending ON command
[31/08/2023, 12:44:33] [Switcher Platform] sending data:
[31/08/2023, 12:44:33] [Switcher Platform] fef05d0002320102000000003400010000000000000000000161f06400000000000000000000f0fe6530650000000000000000000000000000000000000000000000000000000000000000000000000001060001004c0e00004758d5b3
[31/08/2023, 12:44:33] [Switcher Platform] connection closed, had error: false
[31/08/2023, 12:44:33] [Switcher Platform] global close event: false`


Plugin version: homebridge-switcher-platform v4.4.4

**Comment by amitmargalit** [comment] 2023-11-18 19:09
Same here, a new switcher long (V4). The old one worked great

**Comment by Tapuziyahoo** [comment] 2023-12-05 14:40
Same here for all of my Switcher products: status gets updated but not controlled through the Home App.
Works perfect using the Switcher app, tried the "local" on-off solution but that didn't help.

here's a snippet of the logs:

[12/5/2023, 4:37:49 PM] [Switcher Platform] Switcher Switcher Boiler Watts: 0
[12/5/2023, 4:37:49 PM] [Switcher Platform] Switcher Switcher Boiler Volts: 0
[12/5/2023, 4:37:49 PM] [Switcher Platform] Switcher Switcher Boiler Amperes: 0
[12/5/2023, 4:37:49 PM] [Switcher Platform] Switcher Switcher Boiler Total Consumption (KWh): 0
[12/5/2023, 4:37:49 PM] [Switcher Platform] Received a message from 192.168.1.181
[12/5/2023, 4:37:49 PM] [Switcher Platform] {
  device_id: 'c76dc6',
  device_ip: '192.168.1.181',
  name: 'Switcher Runner_529C',
  type: 's11',
  state: {
    light1_power: 'OFF',
    light2_power: 'OFF',
    runner3_position: 100,
    runner3_direction: 'STOP',
    runner3_child_lock: 'OFF'
  }
}
[12/5/2023, 4:37:49 PM] [Switcher Platform] Switcher Light_1D88 - Setting Light1 Power to ON
[12/5/2023, 4:37:49 PM] [Switcher Platform] Sending light power command: true
[12/5/2023, 4:37:49 PM] [Switcher Platform] login...
[12/5/2023, 4:37:49 PM] [Switcher Platform] successful connection, socket was created
[12/5/2023, 4:37:49 PM] [Switcher Platform] sending data
[12/5/2023, 4:37:49 PM] [Switcher Platform] fef030000305a60000000000ff0301000000000000000000bd356f6500000000000000000000f0fe9c0bc800c02d70f0
[12/5/2023, 4:37:49 PM] [Switcher Platform] received login data:
[12/5/2023, 4:37:49 PM] [Switcher Platform] fef04c000402a60000000000ff0302000000000000000000bc356f6500000000000000000000f0fe349454951d88daa02e000200000000000000000000000000000000000000000009b32223
[12/5/2023, 4:37:49 PM] [Switcher Platform] received session id: 00000000
[12/5/2023, 4:37:49 PM] [Switcher Platform] sending data:
[12/5/2023, 4:37:49 PM] [Switcher Platform] fef059000305010200000000000000000000000000000000be356f6500000000000000000000f0fe9c0bc8000000000000000000000000000000000000000000000000000000000000000000000000370a0200010184d61915
[12/5/2023, 4:37:49 PM] [Switcher Platform] connection closed, had error: false
[12/5/2023, 4:37:49 PM] [Switcher Platform] global close event: false
[12/5/2023, 4:37:49 PM] [Switcher Platform] Received a message from 192.168.1.244
[12/5/2023, 4:37:49 PM] [Switcher Platform] {
  device_id: '9f5bc8',
  device_ip: '192.168.1.244',
  name: 'Switcher Light_0D7D',
  type: 'sl03',
  state: { light1_power: 'OFF', light2_power: 'OFF', light3_power: 'OFF' }

**Comment by nitaybz** [comment] 2023-12-12 16:00
Please update to the latest version and let me know if the issue is fixed

**Comment by nitaybz** [comment] 2023-12-12 16:34
Closing cause it's the same as #52

**Closed by nitaybz** 2023-12-12 16:34 UTC

**Comment by amitmargalit** [comment] 2023-12-12 17:25
Upgraded to v4.4.5
Issue persists (switcher v4)
