### ISSUE TITLE
Accessory only shows current state but can't control it only from switcher app 

### ISSUE THREAD

**Issue by baselnama1995** [nitaybz/homebridge-switcher-platform#44] opened 2023-05-22 00:05 UTC
tried local and everything is updated at homebridge and homekit shows the state no control

**Comment by nitaybz** [comment] 2023-06-04 06:01
which accessory? what firmware version you have?

**Comment by nitaybz** [comment] 2023-06-09 20:39
Did you add the token?

**Comment by atjonathanb** [comment] 2023-06-09 22:12
Yup
![image](https://github.com/nitaybz/homebridge-switcher-platform/assets/37149956/2e516586-9ae2-4683-8971-3be94dad6c4e)

**Comment by atjonathanb** [comment] 2023-06-12 08:46
@nitaybz any additional data that you need to assist you more to solve it?

**Comment by nitaybz** [comment] 2023-06-14 08:11
You need to update your firmware version, talk to switcher support

**Comment by odedDilmoni** [comment] 2023-11-15 08:59
Have the same problem with Switcher Mini with a firmware version update.
For me, turning ON the "Local" in the Switcher app settings solved the problem. I can now control the switcher mini and the switcher smart plug from Homebridge again.

**Comment by nitaybz** [comment] 2023-12-12 16:03
Please update to the latest version and let me know if the issue is fixed

**Comment by odedDilmoni** [comment] 2023-12-12 16:29
Turning ON and OFF the "Local" in the Switcher app settings solved the problem.
Anyway, I updates to the latest version and it is still working.
Thanks

**Comment by nitaybz** [comment] 2023-12-12 16:35
Closing cause it's the same as #52

**Closed by nitaybz** 2023-12-12 16:35 UTC
